remote_theme: vaibhavvikas/jekyll-theme-minimalistic

title: Portfolio di Zeruhur
description: Una lista curata dei miei progetti
color-scheme: auto

#logo: /assets/img/logo.png
#favicon: true

platforms:
  - name: Hub Personale
    icon: <i class="fa-solid fa-globe"></i>
    link: https://zeruhur.icu
  - name: holism in the attic (blog)
    icon: <i class="fa-solid fa-globe"></i>
    link: https://blog.zeruhur.icu
  - name: Giardino Digitale
    icon: <i class="fa-solid fa-globe"></i>
    link: https://giardinodigitale.zeruhur.icu
  - name: Zotiquest Games (Etichetta GDR)
    icon: <i class="fa-solid fa-globe"></i>
    link: https://it.zotiquestgames.com
    
navigation:
  - name: Home
    link: ./index.html
  - name: Articoli
    link: ./articoli.html   
  - name: Canali & Comunità
    link: ./canali_comunita.html
  - name: GDR
    link: ./gdr.html
  - name: GDR Solitari
    link: ./gdrs.html
  - name: Traduzioni
    link: ./traduzioni.html 
  - name: Video & Presentazioni
    link: ./video_presentazioni.html    
    #   sublist:
    #     - name: Image
    #       link: ./index.html#small-image