remote_theme: vaibhavvikas/jekyll-theme-minimalistic

title: Zeruhur's Portfolio
description: Una lista curata dei miei progetti GDR
color-scheme: auto

#logo: /assets/img/logo.png
#favicon: true

platforms:
  - name: Pagina Personale
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/vaibhavvikas
  - name: Zotiquest Games
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/vaibhavvikas
  - name: Italian Translation Alliance
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/vaibhavvikas
  - name: itch.io
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/vaibhavvikas
  - name: Syrinx (blog italiano)
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/vaibhavvikas
  - name: Zotiquest (blog inglese)
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/vaibhavvikas
    
navigation:
  - name: Home
    link: ./index.html
 #   sublist:
 #     - name: Image
 #       link: ./index.html#small-image
  - name: Another Page
    link: ./another-page.html
